spring.application.name=backend

#spring.profile.active=local

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=urlShortener

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


app.public-base-url=http://localhost:8080
